project:
  name: "Time_Series_Automata"
  # Veri setlerinin aranacağı yol
  data_dir: "../data/raw"

experiment:
  random_seeds: [42, 123]
  # Model dayanıklılığını ölçmek için senaryolarımız
  scenarios:
    - "original"
    - "gaussian_noise"
    - "unseen_data"
  gaussian_noise:
    # Elektriksel gürültü sebebiyle üretilen hatalı sinyalleri simüle eden 2 değer
    mean: 0.0
    std: 0.1
  # SKAB veri setini kaç oranında bölmeli
  skab_train_val_split: 0.8
  # Test verisinin genliğini 1.5 katsayısıyla çarpar (yani %50 büyütür)
  unseen_data_scale: 1.5

deep_learning:
  epoch_limit: 15
  batch_size: 32
  early_stopping_patience: 3
  learning_rate: 0.0005
  # 0.0 ile 1.0 arasındaki anomali olasılık skorunu ikili koda (binary) çevirir
  classification_threshold: 0.5
  lstm:
    hidden_size: 32
    num_layers: 1
    dropout: 0.0
  cnn_1d:
    filters: 32
    kernel_size: 3

automata:
  window_size_variants: [4, 5]
  alphabet_size_variants: [3, 4]
  default_window_size: 4
  default_alphabet_size: 3
  anomaly_threshold: 0.01
  paa_window_size: 4
  smoothing_k: 0.1
